services:
  postgres-db:
    image: d4ntatar/homelibraryservice_db_jwt
    restart: always
    networks:
      - nestjs-postgres-network
    env_file:
      - .env
  nestjs-app:
    image: d4ntatar/homelibraryservice_app_jwt
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - POSTGRES_HOST=postgres-db
    networks:
      - nestjs-postgres-network
    volumes:
      - backend-logs:/app/dist/infrastructure/logger
      - backend-migrations:/app/dist/infrastructure/database/migrations
    depends_on:
      - postgres-db
    env_file:
      - .env

volumes:
  backend-logs:
  backend-migrations:

networks:
  nestjs-postgres-network:
    driver: bridge